version: '3.0.0'
name: mytattoo

networks:
  network:
    driver: bridge

services:
  database:
    container_name: mydatabase
    image: postgres
    restart: always
    networks:
      - 'network'
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./database/postgres:/database/postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  api:
    build: .
    container_name: myapi
    restart: always
    networks:
      - 'network'
    ports:
      - ${PORT}:3001
    volumes:
      - ./src:/app/backend/src
    links:
      - database
    depends_on:
      - database
    command: sh -c "yarn docker:afterUp"
