version: '3'

networks:
  network:
    driver: bridge

services:
  database:
    container_name: mydatabase
    image: postgres
    restart: always
    networks:
      - 'network'
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./database:/app/database
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  api:
    container_name: myapi
    user: 'node'
    image: 'node:16'
    restart: always
    working_dir: /app/api
    networks:
      - 'network'
    ports:
      - ${API_PORT}:3001
    depends_on:
      - database
    links:
      - database
    volumes:
      - .:/app/api
    command: sh -c "${DOCKER_AFTER_UP}"
